version: "3"
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: "postgres"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
volumes:
  database:
    driver: local
